"""add project status

Revision ID: 18289135b12f
Revises: 6d269c07ec19
Create Date: 2026-08-28 17:03:18.056006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18289135b12f'
down_revision = '6d269c07ec19'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
