"""replace co-leader flag with granular permissions

Revision ID: 6d269c07ec19
Revises: a9f89c387dd0
Create Date: 2026-08-28 06:41:23.891999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d269c07ec19'
down_revision = 'a9f89c387dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_sections', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_review_work', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_co_leader')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_co_leader', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('can_review_work')
        batch_op.drop_column('can_manage_sections')

    # ### end Alembic commands ###

def upgrade():
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_column('is_co_leader')
        batch_op.add_column(sa.Column('can_manage_sections', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_review_work', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.alter_column('can_manage_sections', server_default=None)
        batch_op.alter_column('can_review_work', server_default=None)