"""add template sharing

Revision ID: 77a5f72d74b4
Revises: 05a59486ad4d
Create Date: 2026-08-28 22:36:01.496194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a5f72d74b4'
down_revision = '05a59486ad4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'user_id', name='uq_template_user')
    )
    with op.batch_alter_table('template_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_access_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_access_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_template_access_template_id'))

    op.drop_table('template_access')
    # ### end Alembic commands ###
