"""add co-leader flag

Revision ID: a9f89c387dd0
Revises: 466165427734
Create Date: 2026-08-28 01:14:13.483463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f89c387dd0'
down_revision = '466165427734'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_co_leader', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Drop the server_default after backfilling, so it doesn't linger as an
    # implicit default for new rows going forward (the model's Python-side
    # default=False already handles that for the app).
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.alter_column('is_co_leader', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_column('is_co_leader')

    # ### end Alembic commands ###
